version: 2
models:
  - name: customers_data
    columns:
      - name: id
        description: Unique id for each customer
      - name: first_name
        description: customer first name
      - name: last_name
        description: customer last name
  - name: payments_data
    columns:
      - name: id
        description: Unique id for each transaction
      - name: orderid
        description: order id
      - name: paymentmethod
        description: method of payment
      - name: status
        descriptions: status of the payment
      - name: amount
        description: amount in rupees
      - name: created
        description: date of the payment
  - name: orders_data
    columns:
      - name: id
        description: Unique id for each order
      - name: user_id
        description: user_id
      - name: order_date
        description: date of the order
      - name: status
        descriptions: status of the order
